add npm install in readme
legalthings/angular-pdfjs-viewer pull request #54
Opened 2017-07-21 14:40 UTC by mzmousa

2017-07-27 08:25 UTC, bastienmoulia requested changes
https://www.npmjs.com/package/angular-pdfjs-viewer is not the last version of the package because there is no official one.
`npm install github:legalthings/angular-pdfjs-viewer --save` may be a better way.

2017-08-04 14:42 UTC, cyrilgandon commented
Can we have an official package? It's misleading, I just lost 1 hour before realizing that the version I got through npm is not the same as the docs described.

2017-08-09 16:52 UTC, jasny commented
I've requested the package maintainer to transfer control.

2017-11-20 08:54 UTC, svenstm approved these changes

2017-11-20 08:54 UTC, merged